import { Schema, model, Document } from 'mongoose';

export interface IActivity {
  timeSlot: 'Morning' | 'Afternoon' | 'Evening' | 'Night';
  activityName: string;
  coords: { lat: number; lng: number };
  cost: number;
  durationMinutes: number;
  isIndoorFallback: boolean;
  category: 'Food' | 'Transport' | 'Hotel' | 'Sightseeing' | 'Adventure' | 'Shopping';
  description: string;
}

export interface IItineraryDay {
  day: number;
  date: Date;
  weatherSnapshot: { condition: string; temp: number };
  schedule: IActivity[];
}

export interface IPackingItem {
  id: string;
  item: string;
  category: string;
  packed: boolean;
  autoGenerated: boolean;
}

export interface IExpense {
  id: string;
  amount: number;
  category: string;
  description: string;
  date: Date;
}

export interface ITrip extends Document {
  userId: Schema.Types.ObjectId | string;
  title: string;
  meta: {
    source: string;
    destination: string;
    startDate: Date;
    endDate: Date;
    budgetLimit: number;
    currentSpent: number;
  };
  logistics: {
    currencyCode: string;
    accommodation: {
      name: string;
      coords: { lat: number; lng: number };
      tier: 'Budget' | 'Standard' | 'Luxury';
    };
  };
  itinerary: IItineraryDay[];
  packingList: IPackingItem[];
  expenses: IExpense[];
  createdAt: Date;
}

const ActivitySchema = new Schema<IActivity>({
  timeSlot: { type: String, enum: ['Morning', 'Afternoon', 'Evening', 'Night'], required: true },
  activityName: { type: String, required: true },
  coords: {
    lat: { type: Number, required: true },
    lng: { type: Number, required: true }
  },
  cost: { type: Number, required: true, default: 0 },
  durationMinutes: { type: Number, required: true, default: 60 },
  isIndoorFallback: { type: Boolean, default: false },
  category: { type: String, enum: ['Food', 'Transport', 'Hotel', 'Sightseeing', 'Adventure', 'Shopping'], required: true },
  description: { type: String, default: '' }
});

const ItineraryDaySchema = new Schema<IItineraryDay>({
  day: { type: Number, required: true },
  date: { type: Date, required: true },
  weatherSnapshot: {
    condition: { type: String, default: 'Clear' },
    temp: { type: Number, default: 22 }
  },
  schedule: [ActivitySchema]
});

const PackingItemSchema = new Schema<IPackingItem>({
  id: { type: String, required: true },
  item: { type: String, required: true },
  category: { type: String, required: true },
  packed: { type: Boolean, default: false },
  autoGenerated: { type: Boolean, default: true }
});

const ExpenseSchema = new Schema<IExpense>({
  id: { type: String, required: true },
  amount: { type: Number, required: true },
  category: { type: String, required: true },
  description: { type: String, default: '' },
  date: { type: Date, required: true }
});

const TripSchema = new Schema<ITrip>({
  userId: { type: Schema.Types.Mixed, required: true },
  title: { type: String, required: true },
  meta: {
    source: { type: String, required: true },
    destination: { type: String, required: true },
    startDate: { type: Date, required: true },
    endDate: { type: Date, required: true },
    budgetLimit: { type: Number, required: true },
    currentSpent: { type: Number, default: 0 }
  },
  logistics: {
    currencyCode: { type: String, default: 'USD' },
    accommodation: {
      name: { type: String, required: true },
      coords: {
        lat: { type: Number, required: true },
        lng: { type: Number, required: true }
      },
      tier: { type: String, enum: ['Budget', 'Standard', 'Luxury'], default: 'Standard' }
    }
  },
  itinerary: [ItineraryDaySchema],
  packingList: [PackingItemSchema],
  expenses: [ExpenseSchema],
  createdAt: { type: Date, default: Date.now }
});

export const Trip = model<ITrip>('Trip', TripSchema);
