import { Request, Response } from 'express';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import mongoose from 'mongoose';
import { User } from '../models/User';
import { Trip } from '../models/Trip';
import { sendOtpEmail } from '../utils/mailer';
import { isDbConnected, mockUsers, mockTrips } from '../utils/mockDb';

const JWT_SECRET = process.env.JWT_SECRET || 'voyage-ai-super-secret-key-123456';

const generateOtp = () => Math.floor(100000 + Math.random() * 900000).toString();

const seedDefaultTripForUser = async (userId: any) => {
  try {
    const defaultTrip = {
      userId,
      title: 'Demo Tour: Discovery of Tokyo',
      meta: {
        source: 'New York',
        destination: 'Tokyo',
        startDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000),
        endDate: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000),
        budgetLimit: 3000,
        currentSpent: 450
      },
      logistics: {
        currencyCode: 'USD',
        accommodation: {
          name: 'Tokyo Plaza Hotel Central',
          coords: { lat: 35.6812, lng: 139.7671 },
          tier: 'Standard',
          price: 120
        }
      },
      itinerary: [
        {
          day: 1,
          date: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000),
          weatherSnapshot: { condition: 'Clear', temp: 22 },
          schedule: [
            {
              timeSlot: 'Morning',
              activityName: 'Exploring Historic Senso-ji Temple',
              coords: { lat: 35.7148, lng: 139.7967 },
              cost: 15,
              durationMinutes: 120,
              isIndoorFallback: false,
              category: 'Sightseeing',
              description: 'Explore the oldest and most significant Buddhist temple in Tokyo.'
            },
            {
              timeSlot: 'Afternoon',
              activityName: 'Sushi Lunch at Tsukiji Outer Market',
              coords: { lat: 35.6655, lng: 139.7702 },
              cost: 45,
              durationMinutes: 90,
              isIndoorFallback: false,
              category: 'Food',
              description: 'Sample incredibly fresh sushi and sashimi street food.'
            },
            {
              timeSlot: 'Evening',
              activityName: 'Stroll around Shinjuku Gyoen National Garden',
              coords: { lat: 35.6852, lng: 139.7101 },
              cost: 20,
              durationMinutes: 120,
              isIndoorFallback: false,
              category: 'Nature',
              description: 'Walk through pristine gardens blending traditional Japanese, English, and French styles.'
            }
          ]
        }
      ],
      packingList: [
        { item: 'Passport & Visas', category: 'Essentials', packed: true, autoGenerated: true },
        { item: 'Walking Shoes', category: 'Shoes', packed: true, autoGenerated: true },
        { item: 'Plug Adapter (Type A/B)', category: 'Tech', packed: false, autoGenerated: true }
      ],
      expenses: [
        { id: 'exp_1', amount: 450, category: 'Hotel', description: 'Plaza Reservation Deposit', date: new Date() }
      ]
    };

    const isConnected = mongoose.connection.readyState === 1;
    if (isConnected) {
      const tripCount = await Trip.countDocuments({ userId });
      if (tripCount === 0) {
        const trip = new Trip(defaultTrip);
        await trip.save();
        console.log(`Seeded default Tokyo trip for user ${userId}`);
      }
    } else {
      const tripCount = mockTrips.filter((t: any) => t.userId === userId).length;
      if (tripCount === 0) {
        const trip = {
          _id: 'mock_trip_seed_' + Date.now(),
          ...defaultTrip,
          itinerary: defaultTrip.itinerary.map((day, dIdx) => ({
            ...day,
            _id: `day_${dIdx}_${Date.now()}`,
            schedule: day.schedule.map((act, aIdx) => ({
              ...act,
              _id: `act_${dIdx}_${aIdx}_${Date.now()}`
            }))
          })),
          packingList: defaultTrip.packingList.map((p, idx) => ({ ...p, id: `pack_${idx}_${Date.now()}` })),
          createdAt: new Date()
        };
        mockTrips.push(trip);
        console.log(`Seeded default mock Tokyo trip for user ${userId}`);
      }
    }
  } catch (err) {
    console.error('Failed to seed default trip for user:', err);
  }
};

export const register = async (req: Request, res: Response) => {
  try {
    const { name, email, password } = req.body;
    if (!name || !email || !password) {
      return res.status(400).json({ success: false, message: 'All fields are required.' });
    }

    const emailLower = email.toLowerCase();
    const otp = generateOtp();
    const otpExpires = new Date(Date.now() + 15 * 60 * 1000); // 15 mins
    const passwordHash = await bcrypt.hash(password, 10);

    if (isDbConnected()) {
      const existingUser = await User.findOne({ email: emailLower });
      if (existingUser) {
        return res.status(400).json({ success: false, message: 'Email already registered.' });
      }

      const user = new User({
        name,
        email: emailLower,
        passwordHash,
        isVerified: false,
        verificationOtp: otp,
        verificationOtpExpires: otpExpires,
        role: emailLower.includes('admin') ? 'admin' : 'user'
      });
      await user.save();
    } else {
      const existingUser = mockUsers.find(u => u.email === emailLower);
      if (existingUser) {
        return res.status(400).json({ success: false, message: 'Email already registered.' });
      }

      const newUser = {
        _id: 'mock_user_' + Date.now(),
        name,
        email: emailLower,
        passwordHash,
        isVerified: false,
        verificationOtp: otp,
        verificationOtpExpires: otpExpires,
        preferences: { diet: 'None', accessibility: [], travelStyle: [] },
        savedPlaces: [],
        achievements: [],
        role: emailLower.includes('admin') ? 'admin' : 'user',
        createdAt: new Date()
      };
      mockUsers.push(newUser);
    }

    await sendOtpEmail(emailLower, otp, 'verify');

    return res.status(201).json({
      success: true,
      message: 'Registration successful. OTP sent to email.',
      email: emailLower
    });
  } catch (error: any) {
    console.error('Register error:', error);
    return res.status(500).json({ success: false, message: 'Server error: ' + error.message });
  }
};

export const verifyOtp = async (req: Request, res: Response) => {
  try {
    const { email, otp } = req.body;
    if (!email || !otp) {
      return res.status(400).json({ success: false, message: 'Email and OTP are required.' });
    }

    const emailLower = email.toLowerCase();
    let user: any = null;

    if (isDbConnected()) {
      user = await User.findOne({ email: emailLower });
    } else {
      user = mockUsers.find(u => u.email === emailLower);
    }

    if (!user) {
      return res.status(404).json({ success: false, message: 'User not found.' });
    }

    if (user.verificationOtp !== otp) {
      return res.status(400).json({ success: false, message: 'Invalid OTP.' });
    }

    if (new Date() > new Date(user.verificationOtpExpires)) {
      return res.status(400).json({ success: false, message: 'OTP expired.' });
    }

    user.isVerified = true;
    user.verificationOtp = undefined;
    user.verificationOtpExpires = undefined;

    if (isDbConnected()) {
      await user.save();
    }

    await seedDefaultTripForUser(user._id);

    const token = jwt.sign(
      { id: user._id, email: user.email, role: user.role },
      JWT_SECRET,
      { expiresIn: '7d' }
    );

    res.cookie('token', token, {
      httpOnly: true,
      secure: process.env.NODE_ENV === 'production',
      maxAge: 7 * 24 * 60 * 60 * 1000 // 7 days
    });

    return res.json({
      success: true,
      message: 'OTP verified. Account activated.',
      token,
      user: {
        id: user._id,
        name: user.name,
        email: user.email,
        role: user.role,
        preferences: user.preferences || { diet: 'None', accessibility: [], travelStyle: [] },
        achievements: user.achievements || []
      }
    });
  } catch (error: any) {
    console.error('Verify OTP error:', error);
    return res.status(500).json({ success: false, message: 'Server error.' });
  }
};

export const login = async (req: Request, res: Response) => {
  try {
    const { email, password } = req.body;
    if (!email || !password) {
      return res.status(400).json({ success: false, message: 'Email and password are required.' });
    }

    const emailLower = email.toLowerCase();
    let user: any = null;

    if (isDbConnected()) {
      user = await User.findOne({ email: emailLower });
    } else {
      user = mockUsers.find(u => u.email === emailLower);
    }

    if (!user) {
      return res.status(400).json({ success: false, message: 'Invalid email or password.' });
    }

    const isMatch = await bcrypt.compare(password, user.passwordHash);
    if (!isMatch) {
      return res.status(400).json({ success: false, message: 'Invalid email or password.' });
    }

    if (!user.isVerified) {
      const otp = generateOtp();
      user.verificationOtp = otp;
      user.verificationOtpExpires = new Date(Date.now() + 15 * 60 * 1000);
      if (isDbConnected()) {
        await user.save();
      }
      await sendOtpEmail(emailLower, otp, 'verify');
      return res.status(403).json({
        success: false,
        message: 'Account not verified. New OTP sent to email.',
        unverified: true,
        email: emailLower
      });
    }

    const token = jwt.sign(
      { id: user._id, email: user.email, role: user.role },
      JWT_SECRET,
      { expiresIn: '7d' }
    );

    res.cookie('token', token, {
      httpOnly: true,
      secure: process.env.NODE_ENV === 'production',
      maxAge: 7 * 24 * 60 * 60 * 1000 // 7 days
    });

    return res.json({
      success: true,
      message: 'Login successful.',
      token,
      user: {
        id: user._id,
        name: user.name,
        email: user.email,
        role: user.role,
        preferences: user.preferences || { diet: 'None', accessibility: [], travelStyle: [] },
        achievements: user.achievements || []
      }
    });
  } catch (error: any) {
    console.error('Login error:', error);
    return res.status(500).json({ success: false, message: 'Server error.' });
  }
};

export const forgotPassword = async (req: Request, res: Response) => {
  try {
    const { email } = req.body;
    if (!email) {
      return res.status(400).json({ success: false, message: 'Email is required.' });
    }

    const emailLower = email.toLowerCase();
    let user: any = null;

    if (isDbConnected()) {
      user = await User.findOne({ email: emailLower });
    } else {
      user = mockUsers.find(u => u.email === emailLower);
    }

    if (!user) {
      return res.status(404).json({ success: false, message: 'User with this email does not exist.' });
    }

    const otp = generateOtp();
    user.resetPasswordOtp = otp;
    user.resetPasswordOtpExpires = new Date(Date.now() + 15 * 60 * 1000);

    if (isDbConnected()) {
      await user.save();
    }

    await sendOtpEmail(emailLower, otp, 'reset');

    return res.json({
      success: true,
      message: 'Password reset OTP sent to email.',
      email: emailLower
    });
  } catch (error: any) {
    console.error('Forgot password error:', error);
    return res.status(500).json({ success: false, message: 'Server error.' });
  }
};

export const resetPassword = async (req: Request, res: Response) => {
  try {
    const { email, otp, newPassword } = req.body;
    if (!email || !otp || !newPassword) {
      return res.status(400).json({ success: false, message: 'All fields are required.' });
    }

    const emailLower = email.toLowerCase();
    let user: any = null;

    if (isDbConnected()) {
      user = await User.findOne({ email: emailLower });
    } else {
      user = mockUsers.find(u => u.email === emailLower);
    }

    if (!user) {
      return res.status(404).json({ success: false, message: 'User not found.' });
    }

    if (user.resetPasswordOtp !== otp) {
      return res.status(400).json({ success: false, message: 'Invalid OTP.' });
    }

    if (new Date() > new Date(user.resetPasswordOtpExpires)) {
      return res.status(400).json({ success: false, message: 'OTP expired.' });
    }

    const passwordHash = await bcrypt.hash(newPassword, 10);
    user.passwordHash = passwordHash;
    user.resetPasswordOtp = undefined;
    user.resetPasswordOtpExpires = undefined;

    if (isDbConnected()) {
      await user.save();
    }

    return res.json({
      success: true,
      message: 'Password has been reset successfully.'
    });
  } catch (error: any) {
    console.error('Reset password error:', error);
    return res.status(500).json({ success: false, message: 'Server error.' });
  }
};

export const getMe = async (req: any, res: Response) => {
  try {
    const userId = req.user.id;
    let user: any = null;

    if (isDbConnected()) {
      user = await User.findById(userId).select('-passwordHash');
    } else {
      user = mockUsers.find(u => u._id === userId);
    }

    if (!user) {
      return res.status(404).json({ success: false, message: 'User not found.' });
    }

    return res.json({
      success: true,
      user: {
        id: user._id,
        name: user.name,
        email: user.email,
        role: user.role,
        preferences: user.preferences || { diet: 'None', accessibility: [], travelStyle: [] },
        achievements: user.achievements || [],
        savedPlaces: user.savedPlaces || []
      }
    });
  } catch (error: any) {
    console.error('Get me error:', error);
    return res.status(500).json({ success: false, message: 'Server error.' });
  }
};

export const updatePreferences = async (req: any, res: Response) => {
  try {
    const userId = req.user.id;
    const { preferences } = req.body;
    let user: any = null;

    if (isDbConnected()) {
      user = await User.findById(userId);
    } else {
      user = mockUsers.find(u => u._id === userId);
    }

    if (!user) {
      return res.status(404).json({ success: false, message: 'User not found.' });
    }

    user.preferences = {
      ...user.preferences,
      ...preferences
    };

    if (isDbConnected()) {
      await user.save();
    }

    return res.json({
      success: true,
      message: 'Preferences updated successfully.',
      preferences: user.preferences
    });
  } catch (error: any) {
    console.error('Update preferences error:', error);
    return res.status(500).json({ success: false, message: 'Server error.' });
  }
};

export const googleLogin = async (req: Request, res: Response) => {
  try {
    const { email, name } = req.body;
    if (!email || !name) {
      return res.status(400).json({ success: false, message: 'Email and name are required.' });
    }

    const emailLower = email.toLowerCase();
    let user: any = null;

    if (isDbConnected()) {
      user = await User.findOne({ email: emailLower });
    } else {
      user = mockUsers.find(u => u.email === emailLower);
    }

    if (!user) {
      const dummyPassword = Math.random().toString(36).substring(2, 15);
      const passwordHash = await bcrypt.hash(dummyPassword, 10);
      
      if (isDbConnected()) {
        user = new User({
          name,
          email: emailLower,
          passwordHash,
          isVerified: true,
          role: emailLower.includes('admin') ? 'admin' : 'user'
        });
        await user.save();
      } else {
        user = {
          _id: 'mock_google_user_' + Date.now(),
          name,
          email: emailLower,
          passwordHash,
          isVerified: true,
          preferences: { diet: 'None', accessibility: [], travelStyle: [] },
          savedPlaces: [],
          achievements: [],
          role: emailLower.includes('admin') ? 'admin' : 'user',
          createdAt: new Date()
        };
        mockUsers.push(user);
      }
    }

    await seedDefaultTripForUser(user._id);

    const token = jwt.sign(
      { id: user._id, email: user.email, role: user.role },
      JWT_SECRET,
      { expiresIn: '7d' }
    );

    res.cookie('token', token, {
      httpOnly: true,
      secure: process.env.NODE_ENV === 'production',
      maxAge: 7 * 24 * 60 * 60 * 1000 // 7 days
    });

    return res.json({
      success: true,
      message: 'Google login successful.',
      token,
      user: {
        id: user._id,
        name: user.name,
        email: user.email,
        role: user.role,
        preferences: user.preferences || { diet: 'None', accessibility: [], travelStyle: [] },
        achievements: user.achievements || []
      }
    });
  } catch (error: any) {
    console.error('Google login error:', error);
    return res.status(500).json({ success: false, message: 'Server error.' });
  }
};

export const logout = (req: Request, res: Response) => {
  res.clearCookie('token');
  return res.json({ success: true, message: 'Logged out successfully.' });
};
